name: check

on:
  push:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout machina
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: make fmt-check

      - name: Run Clippy
        run: make clippy
