name: docs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout machina
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build documentation
        run: make docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdocs
          path: target/doc
